version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - "8000"
    command: >
      bash -c "./wait-for-it.sh db:3306 -- python3 manage.py makemigrations && python3 manage.py migrate &&gunicorn --bind 0.0.0.0:8000 User_service.wsgi:application "
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
 #     MYSQL_USER: "${DB_USER}"
#      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"



  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
